version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing AWS CLI..."
      - pip install --upgrade pip
      - pip install --upgrade awscli
  build:
    commands:
      #- echo "Deploying DynamoDB Table..."
      #- aws cloudformation deploy --template-file https://mi-nuevo-bucket-s3.s3.amazonaws.com/template.yml --stack-name MyDynamoDBStack --parameter-overrides EnvironmentName=dev --region us-east-1
      - chmod +x validar_stack.sh
      - ./validar_stack.sh
