version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
  pre_build:
    commands:
      - echo "Installing AWS CLI..."
      - sudo yum update -y
      - sudo yum install -y python3-pip
      - pip3 install awscli
  build:
    commands:
      - echo "Deploying DynamoDB Table..."
      - aws cloudformation deploy --template-file https://github.com/aldanaangel/aws_dynamodb/blob/main/template.yaml --stack-name MyDynamoDBStack --parameter-overrides EnvironmentName=dev --region u-east-1
