AWSTemplateFormatVersion: '2010-09-09'
Description: Plantilla para crear dos tablas en Amazon DynamoDB

Resources:
  FirstTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FirstTable
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  SecondTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SecondTable
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
